import 'dart:io';

import 'package:assets_generator/src/arg/type.dart';
import 'package:assets_generator/src/yaml.dart';
import 'package:test/test.dart';

void main() {
  late Directory tmp;

  setUp(() {
    tmp = Directory.systemTemp.createTempSync('assets_generator_test');
  });

  tearDown(() {
    tmp.deleteSync(recursive: true);
  });

  File pubspec(String content) =>
      File('${tmp.path}${Platform.pathSeparator}pubspec.yaml')
        ..writeAsStringSync(content);

  /// Runs the yaml writer [times] times the same way the generator does
  /// (fresh Yaml per run, freshly scanned asset list) and returns the file
  /// content after every run.
  List<String> generate(File file, List<String> assets, int times) {
    final List<String> snapshots = <String>[];
    for (int i = 0; i < times; i++) {
      Yaml(file, assets.toList(), <String>[], FormatType.file).write();
      snapshots.add(file.readAsStringSync());
    }
    return snapshots;
  }

  void expectConverged(List<String> snapshots) {
    for (int i = 1; i < snapshots.length; i++) {
      expect(
        snapshots[i],
        snapshots.first,
        reason: 'run ${i + 1} differs from run 1',
      );
    }
  }

  test('block present with content below it: repeated runs are stable', () {
    final File file = pubspec('''
name: sample

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/a.txt

  # assets end

  # manual comment below the write region
  fonts:
    - family: Foo
      fonts:
        - asset: assets/fonts/Foo.ttf
''');

    final List<String> snapshots = generate(
      file,
      <String>['assets/a.txt', 'assets/images/logo.png'],
      5,
    );

    expectConverged(snapshots);
    expect(snapshots.last, contains('# manual comment below the write region'));
    expect(snapshots.last, contains('fonts:'));
    expect(snapshots.last, contains('- family: Foo'));
    expect(snapshots.last, endsWith('\n'));
  });

  test(
    'inserting into an empty assets key keeps sibling content below intact',
    () {
      final File file = pubspec('''
name: sample

flutter:
  assets:
  uses-material-design: true
''');

      final List<String> snapshots = generate(
        file,
        <String>['assets/images/logo.png'],
        5,
      );

      expectConverged(snapshots);
      expect(snapshots.first, contains('# assets start'));
      expect(snapshots.first, contains('uses-material-design: true'));
      final int blockStart = snapshots.first.indexOf('# assets start');
      final int below = snapshots.first.indexOf('uses-material-design: true');
      expect(below, greaterThan(blockStart));
    },
  );

  test('inserting into flutter keeps top-level keys below it intact', () {
    final File file = pubspec('''
name: sample

flutter:
  uses-material-design: true

custom_fonts:
  myfont: value
''');

    final List<String> snapshots = generate(
      file,
      <String>['assets/images/logo.png'],
      5,
    );

    expectConverged(snapshots);
    expect(snapshots.first, contains('# assets start'));
    expect(snapshots.first, contains('custom_fonts:'));
    expect(snapshots.first, contains('myfont: value'));
    expect(snapshots.first, endsWith('\n'));
  });

  test('block at end of file: repeated runs keep the final newline', () {
    final File file = pubspec('''
name: sample

flutter:
  uses-material-design: true
''');

    final List<String> snapshots = generate(
      file,
      <String>['assets/a.txt'],
      5,
    );

    expectConverged(snapshots);
    expect(snapshots.first, endsWith('# assets end\n'));
  });
}
