import 'package:build_runner_core/build_runner_core.dart';

import 'camel_under_score_converter.dart';

const String license = '''// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
''';

String get classDeclare => 'class Assets {\n Assets._();';
String get classDeclareFooter => '}\n';

class Template {
  Template(this.assets, this.packageGraph);
  final PackageNode packageGraph;
  final List<String> assets;

  @override
  String toString() {
    final StringBuffer sb = StringBuffer();
    sb.write(license);
    sb.write(classDeclare);
    if (!packageGraph.isRoot) {
      sb.write(
          '''static const String packageName = '${packageGraph.name}';\n''');
    }
    for (final String asset in assets) {
      sb.write(formatFiled(asset));
    }

    sb.write(classDeclareFooter);

    return sb.toString();
  }

  String formatFiled(String path) {
    return '''static const String ${_formatFiledName(path)} = '$path';\n''';
  }

  String _formatFiledName(String path) {
    path = path
        .replaceAll('/', '_')
        .replaceAll('.', '_')
        .replaceAll(' ', '_')
        .replaceAll('-', '_')
        .replaceAll('@', '_AT_');
    return camelName(path);
  }

  String toUppercaseFirstLetter(String str) {
    return '${str[0].toUpperCase()}${str.substring(1)}';
  }
}
