// dart format off
// coverage:ignore-file
// ignore_for_file: constant_identifier_names
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************

abstract final class Assets {
  static const String assets_dd_txt = 'assets/dd.txt';

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  static const String assets_images_flutter_candies_logo_png =
      'assets/images/flutter_candies_logo.png';
  static const String assets_test_txt = 'assets/test.txt';
}

final List<String> assetsArray = <String>[
  Assets.assets_dd_txt,

  /// {@macro assets_generator.assets_images_flutter_candies_logo_png.preview}
  Assets.assets_images_flutter_candies_logo_png,
  Assets.assets_test_txt,
];
