// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  Assets._();
  static const String assets_images_flutter_candies_logo_png =
      'assets/images/flutter_candies_logo.png';
  static const String assets_test_txt = 'assets/test.txt';
  static const String assets_dd_txt = 'assets/dd.txt';
}
