// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  Assets._();
  static const String packageName = 'module_a';
  static const String assetsXxxTxt = 'assets/xxx.txt';
  static const String assetsImagesXxxJpg = 'assets/images/xxx.jpg';
  static const String assetsImagesTestTxt = 'assets/images/test.txt';
}
