// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  const Assets._();
  static const String package = 'module_a';
  static const String assets_abc_txt = 'assets/abc.txt';
  static const String assets_images_flutter_candies_logo_png =
      'assets/images/flutter_candies_logo.png';
  static const String assets_images_test_txt = 'assets/images/test.txt';
}
